services:
  db:
    image: mysql:8.1
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      # - MYSQL_USER=${DB_USER}
      # - MYSQL_PASSWORD=${DB_PASSWORD}
      # - MYSQL_DATABASE=${DB_NAME}
    ports:
      - ${DB_PORT}:3306
    # volumes:
    #   - ./db-data:/var/lib/mysql
